name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-arm64:
    runs-on: [self-hosted, linux, arm]
    steps:
    - name: Setup python
      run: |
        pyenv global system
        python --version
        uname -m
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test

  build-linux-x86:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install libunwind-dev
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build --release --verbose --examples
    - name: Test
      id: test
      continue-on-error: true
      run: cargo test --release
    - name: Test (retry#1)
      id: test1
      run: cargo test --release
      if: steps.test.outcome=='failure'
      continue-on-error: true
    - name: Test (retry#2)
      run: cargo test --release
      if: steps.test1.outcome=='failure'
